### PR TITLE
fix: Update plugin state on Python argument changes

### LINKED ISSUE #2587: some marimo components do not update with some arguments
### Describe the bug

When updating certain arguments for components like `mo.ui.table` and `mo.ui.file_browser`, the outputted component is not re-rendered.

For example, running a cell with:
```py
mo.ui.table(df)
```
And then updating the code to:
```py
mo.ui.table(df, freeze_columns_left=["name"])
```
will not freeze a column to the left.

However, things like page size, label, etc. work fine. Expect behavior to be the same as components such as dropdown or slider, where updating the options or min/max will immediately update the component.

Might have something to do with how these components use rpc to call backend functions to update state? Working on a fix.

### Environment

```json
{
  "marimo": "0.9.4",
  "OS": "Darwin",
  "OS Version": "23.6.0",
  "Processor": "arm",
  "Python Version": "3.12.3",
  "Binaries": {
    "Browser": "129.0.6668.91",
    "Node": "v22.2.0"
  },
  "Dependencies": {
    "click": "8.1.3",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.9",
    "ruff": "0.6.5",
    "starlette": "0.38.5",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "anywidget": "0.9.13",
    "duckdb": "1.1.1",
    "ibis-framework": "9.5.0",
    "pandas": "2.2.2",
    "polars": "1.5.0",
    "pyarrow": "17.0.0"
  }
}
```

### Code to reproduce

```python
import marimo

__generated_with = "0.9.4"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    from vega_datasets import data
    return data, mo


@app.cell
def __(data, mo):
    datasets = data.list_datasets()
    dropdown = mo.ui.dropdown(value="cars", options=datasets, full_width=True)
    dropdown
    return datasets, dropdown


@app.cell
def __(data, dropdown, mo):
    dataset = getattr(data, dropdown.value)
    mo.ui.table(
        dataset(), freeze_columns_left=["STATION"], freeze_columns_right=["DATE"]
    )
    return (dataset,)


@app.cell
def __(mo):
    b = mo.ui.file_browser(filetypes=[".txt", ".md"], selection_mode="directory")
    b
    return (b,)


if __name__ == "__main__":
    app.run()
```

### LINKED ISSUE #2648: ui.file_browser is not responsive on initial_path from ui.text
### Describe the bug

If I take the inital_path from ui.text() response, the file_browser is not reset to that new location. E.g. if I put another Drive letter to the text-input.

### Environment

marimo 0.9.9

### Code to reproduce

```
import marimo as mo
```

```
source = mo.ui.text()
source
```

```
mo.ui.file_browser(initial_path=source.value)
```

### PR DESCRIPTION
**Pull request by wasimxyz**
## 📝 Summary

Fixes #2587
Fixes #2648

## 🔍 Description of Changes

Noticed that some plugins were not updating with changes to the initialization arguments. `DataTablePlugin` handled this using effects, so I just extended that for the args that were not updating state.

- Update `mo.ui.table` on change to `freeze_columns_left` or `freeze_columns_right`.
- Update `mo.ui.file_browser` on change to `initial_path`, `multiple`, `restrict_navigation`, and `selection_mode`.

## 📋 Checklist

- [x] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [x] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://discord.gg/JE7nhX6mD8), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [ ] I have added tests for the changes made.
- [x] I have run the code and verified that it works as expected.

## 📜 Reviewers

@akshayka OR @mscolnick

### CODE REVIEW

File: frontend/src/plugins/impl/FileBrowserPlugin.tsx [hunk 1]
```diff
@@ -138,6 +138,25 @@ export const FileBrowser = ({
   const [path, setPath] = useState(initialPath);
   const [selectAllLabel, setSelectAllLabel] = useState("Select all");
   const [isUpdatingPath, setIsUpdatingPath] = useState(false);
+  const [isRestricted, setIsRestricted] = useState(restrictNavigation);
+  const [allowMultiSelect, setAllowMultiSelect] = useState(multiple);
+  const [selectMode, setSelectMode] = useState(selectionMode);
+
+  useEffect(() => {
```
Comment (mscolnick) [inline frontend/src/plugins/impl/FileBrowserPlugin.tsx:145]: could we use `useControllableState`?
or could we write our own hook for this? 

it would be nice to document these useEffects. the react team has started to discourage useEffects to trigger state changes, it might be better to do something like this (untested):

```ts
export const useInternalState<T>(initial: T) {
  const [state, setState] = useState(initial);
  const ref = useRef(initial);

  // Whenever the outside state changes, update the internal state
  if (ref.current !== initial) {
    setState(initial); // react is ok to setState during render
    ref.current = initial;
  }

  return [state, setState];
}
```

Comment (mscolnick) [reply frontend/src/plugins/impl/FileBrowserPlugin.tsx]: i just pushed up these changes
