### PR TITLE
fix: accordion max-width styling

### LINKED ISSUE #2216: Math not displaying correctly in accordion
### Describe the bug

Inline math is not displaying correctly in the summary of an accordion like in here:
image

### Environment

```json
{
  "marimo": "0.8.9",
  "OS": "Linux",
  "OS Version": "6.9.3-76060903-generic",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pymdown-extensions": "10.9",
    "pygments": "2.18.0",
    "tomlkit": "0.13.2",
    "uvicorn": "0.30.6",
    "starlette": "0.38.4",
    "websockets": "13.0.1",
    "typing-extensions": "4.12.2",
    "ruff": "0.6.3"
  }
}
```

### Code to reproduce

```python
mo.accordion(
    {
        r"""**a)** Estime os coeficientes da regressão de $Y$ sobre $X_1$, bem como o erro padrão da regressão e o $R^2$. O que pensa da estimativa de $\beta_1$?""": mo.md(
            """
            - Introduzindo o comando `regress Y X1` obtemos a estimação abaixo
            - A estimativa para $\beta_1$ é inesperada, pois contradiz a teoria económica de que existe uma relação negativa entre o preço e as vendas.
            """
        )
    }
)
```

### LINKED ISSUE #2217: Irresponsive width in accordion summary text
### Describe the bug

Adjusting the window size to `compact`, `medium` or `full` has no impact on the width of the accordion summary (not like that on the details).
Screenshot from 2024-09-04 15-55-46
Screenshot from 2024-09-04 15-56-06
Screenshot from 2024-09-04 15-56-21

### Environment

```json
{
  "marimo": "0.8.9",
  "OS": "Linux",
  "OS Version": "6.9.3-76060903-generic",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pymdown-extensions": "10.9",
    "pygments": "2.18.0",
    "tomlkit": "0.13.2",
    "uvicorn": "0.30.6",
    "starlette": "0.38.4",
    "websockets": "13.0.1",
    "typing-extensions": "4.12.2",
    "ruff": "0.6.3"
  }
}
```

### Code to reproduce

```pyhton
mo.accordion(
    {
        """**e)** Diria que o trabalho, a educação e a idade explicam muita da variação no sono? Que outros fatores poderiam afetar o tempo passado a dormir? Estarão esses fatores provavelmente correlacionados com o trabalho?""": """
    - O $R^2 = 0.113$ é reduzido
    - Só 11.3% da variabilidade do sono é explicada pelas variáveis explicativas escolhidas para o modelo
    - Há fatores que ficaram de fora do modelo que podem influenciar o sono. Exemplos:
        - _Stress_
        - Idade dos filhos
        - Profissão
    - Vários destes fatores podem estar relacionado com o número de horas de trabalho, o que compromete o pressuposto $\mathbb{E}(u|trab)=0$ e, assim, coloca em causa a validade do modelo.
    """
    }
)
```

### PR DESCRIPTION
**Pull request by mscolnick**
Fixes #2217
Fixes #2216

Unset the max-width for buttons that is added by `.prose`

Small drive-by to add a tooltip to the running cell's indicator

image

### CODE REVIEW

File: frontend/src/components/editor/chrome/wrapper/sidebar.tsx [hunk 1]
```diff
@@ -48,14 +48,28 @@ export const Sidebar: React.FC = () => {
...
+    >
+      <div className="flex flex-col-reverse gap-[1px] overflow-hidden">
+        {Array.from({ length: count }).map((_, index) => (
+          <div
+            key={index.toString()}
+            className="flex-shrink-0 h-1 w-2 bg-[var(--grass-6)] border border-[var(--grass-7)]"
+          />
+        ))}
+      </div>
+    </Tooltip>
```
Comment (mscolnick) [inline frontend/src/components/editor/chrome/wrapper/sidebar.tsx:72]: cc @dmadisetti

**Review by akshayka — APPROVED** [review]
