### PR TITLE
fix: show hidden cells when markdown has no output

### LINKED ISSUE #3317: Hidden markdown without outputs should be visible
### Describe the bug

* Disable autorun on startup
* Run `marimo tutorial intro`
* Notice that hidden markdown cells (which don't have outputs) are invisible

Image

There was an initial attempt to unhide markdown code that didn't have outputs, but that was a bit buggy and was reverted in 0ee0ded315ad766da386bf774da5982c90c4c654.

We should fix this before making autorun on startup > disabled the default.

### Environment

<details>

```
{
  "marimo": "0.10.9",
  "OS": "Darwin",
  "OS Version": "22.5.0",
  "Processor": "arm",
  "Python Version": "3.11.8",
  "Binaries": {
    "Browser": "131.0.6778.205",
    "Node": "v21.5.0"
  },
  "Dependencies": {
    "click": "8.1.8",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.20.1",
    "packaging": "24.2",
    "psutil": "6.1.1",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.13",
    "pyyaml": "6.0.2",
    "ruff": "0.8.4",
    "starlette": "0.45.1",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.34.0",
    "websockets": "14.1"
  },
  "Optional Dependencies": {}
}```

</details>


### Code to reproduce

Edit any notebook that has markdown with autorun on startup disabled.

### PR DESCRIPTION
**Pull request by Light2Dark**
## 📝 Summary

Fixes #3317 . Should display hidden cells similar to pre-borderless-markdown era. Code may be a bit rough.
Screenshot 2025-01-01 at 2 05 14 AM

## 📋 Checklist

- [X] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [ ] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [ ] I have added tests for the changes made.
- [X] I have run the code and verified that it works as expected.

## 📜 Reviewers

@akshayka OR @mscolnick

### CODE REVIEW

File: frontend/src/components/editor/cell/code/cell-editor.tsx [hunk 1]
```diff
@@ -359,6 +361,17 @@ const CellEditorInternal = ({
     };
   }, [editorViewRef]);
 
+  // Completely hide the editor & icons if it's markdown and hidden. If there is output, we show.
+  const showHideButton =
```
Comment (Light2Dark) [inline frontend/src/components/editor/cell/code/cell-editor.tsx:365]: wonder if these should be memoized..

Comment (akshayka) [reply frontend/src/components/editor/cell/code/cell-editor.tsx:365]: These are just boolean operations, should be super cheap.

**Review by akshayka — APPROVED** [review]
LGTM. Thank you!
