### PR TITLE
fix dependency panel edges

### LINKED ISSUE #6692: Dependency graph no longer render the edges
### Describe the bug

In the latest version of marimo the depedency graph no longer draws the edges between cells:

Image

molab: https://molab.marimo.io/notebooks/nb_HFwGgMNL9dJ7kXFaJmgRgM

### Will you submit a PR?

- [ ] Yes

### Environment

https://molab.marimo.io/notebooks/nb_HFwGgMNL9dJ7kXFaJmgRgM

### Code to reproduce

_No response_

### PR DESCRIPTION
**Pull request by Light2Dark**
## 📝 Summary

Fixes #6692. Use static ids instead of useId. Reverts a previous lint fix.

CleanShot 2025-10-13 at 11 35 05

## 📋 Checklist

- [x] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [ ] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [ ] I have added tests for the changes made.
- [x] I have run the code and verified that it works as expected.

### CODE REVIEW

File: frontend/src/components/dependency-graph/custom-node.tsx [hunk 1]
```diff
@@ -37,24 +37,21 @@ export const CustomNode = memo((props: CustomNodeProps) => {
...
-  const outputTwoId = useId();
-
   const linesOfCode = cell.code.split("\n").length;
   return (
     <div>
+      {/** biome-ignore lint/correctness/useUniqueElementIds: Static ids are used for edge connections */}
       <Handle
         type="target"
-        id={inputOneId}
+        id="inputs"
```
Comment (mscolnick) [inline frontend/src/components/dependency-graph/custom-node.tsx]: Maybe worth adding note or moving to the top of the file to avoid it being migrated by accident

Comment (Light2Dark) [reply frontend/src/components/dependency-graph/custom-node.tsx]: thanks, moved to constants
