### PR TITLE
fix: cell-id logic in function-registry

### LINKED ISSUE #6462: Upgrade to 0.16 gives "Error Cell Id should exist" when sorting dataframe
### Describe the bug

Sorting a Polars dataframe on a column gives "Error Cell Id should exist" (sort not performed). Reverted to 0.15.5 and error is not present

Image

Note: Only appears to happen when datafram is contained within an mo.accordion, if I use without the accordion  then no error is observed.

### Will you submit a PR?

- [ ] Yes

### Environment

macOS  15.6.1 (24G90), Chrome Version 140.0.7339.186 (Official Build) (arm64)

```
{
  "marimo": "0.16.0",
  "editable": false,
  "location": "/Users/mauriceh@nisos.com/.cache/uv/archive-v0/q2dv1z_9xjIjF3dlm3eS1/lib/python3.13/site-packages/marimo",
  "OS": "Darwin",
  "OS Version": "24.6.0",
  "Processor": "arm",
  "Python Version": "3.13.5",
  "Binaries": {
    "Browser": "140.0.7339.186",
    "Node": "v24.8.0"
  },
  "Dependencies": {
    "click": "8.3.0",
    "docutils": "0.22.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.9",
    "narwhals": "2.5.0",
    "packaging": "25.0",
    "psutil": "7.1.0",
    "pygments": "2.19.2",
    "pymdown-extensions": "10.16.1",
    "pyyaml": "6.0.2",
    "starlette": "0.48.0",
    "tomlkit": "0.13.3",
    "typing-extensions": "missing",
    "uvicorn": "0.36.0",
    "websockets": "15.0.1"
  },
  "Optional Dependencies": {
    "loro": "1.6.0"
  },
  "Experimental Flags": {}
}
```

</details>

### Code to reproduce

_No response_

### PR DESCRIPTION
**Pull request by mscolnick**
Fixes #6462 introduced in https://github.com/marimo-team/marimo/issues/6281

### CODE REVIEW

File: frontend/src/plugins/core/registerReactComponent.tsx [hunk 1]
```diff
@@ -182,24 +182,26 @@ function PluginSlotInternal<T>(
...
+            status: cellRuntime.status,
+            errored: cellRuntime.errored,
+            interrupted: cellRuntime.interrupted,
+            stopped: cellRuntime.stopped,
+          });
+
+          if (cellNotInitialized) {
+            throw new CellNotInitializedError();
+          }
         }
```
Comment (Light2Dark) [inline frontend/src/plugins/core/registerReactComponent.tsx:207]:
```suggestion
        } else {
             Logger.warn(`Cell ID ${cellId} cannot be found`);
        }
```

**Review by Light2Dark — APPROVED** [review]
