### PR TITLE
Fix anywidget initial buffer handling regression

### LINKED ISSUE #6499: Widget not displaying in marimo 0.15.3 or newer
### Describe the bug

Hi,
I noticed that my widget stopped working in marimo recently. Tracked it down to marimo 0.15.3 as the first version where it breaks. At first I thought it's something I changed in the widget recently, but the widget renders correctly in with marimo v0.15.2, jupyter, and [colab](https://colab.research.google.com/drive/1EZh9HcGS3cgPF4C6eFyMm5iHGVGS4Cj_?usp=sharing). Also still happens with marimo 0.16.1.

Minimal reproducible example:
https://gist.github.com/dvdkouril/27db97e757071abc1cf67c6b5f6ca718

`uvx marimo@0.15.2 edit https://gist.githubusercontent.com/dvdkouril/27db97e757071abc1cf67c6b5f6ca718/raw/30a30667b393b82d9d617819089ce1870cf913fc/uchimata-example.py`

Image

`uvx marimo@0.15.3 edit https://gist.githubusercontent.com/dvdkouril/27db97e757071abc1cf67c6b5f6ca718/raw/30a30667b393b82d9d617819089ce1870cf913fc/uchimata-example.py`

Image

### Will you submit a PR?

- [ ] Yes

### Environment

<details>

```
{
  "marimo": "0.16.1",
  "editable": false,
  "location": "/Users/davidkouril/projects/dvdkouril/brain-lifespan-3d-chromatin/.venv/lib/python3.13/site-packages/marimo",
  "OS": "Darwin",
  "OS Version": "24.6.0",
  "Processor": "arm",
  "Python Version": "3.13.0",
  "Locale": "en_US",
  "Binaries": {
    "Browser": "140.0.7339.186",
    "Node": "v22.17.1"
  },
  "Dependencies": {
    "click": "8.3.0",
    "docutils": "0.22.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.9",
    "narwhals": "2.5.0",
    "packaging": "25.0",
    "psutil": "7.1.0",
    "pygments": "2.19.2",
    "pymdown-extensions": "10.16.1",
    "pyyaml": "6.0.2",
    "starlette": "0.48.0",
    "tomlkit": "0.13.3",
    "typing-extensions": "4.15.0",
    "uvicorn": "0.35.0",
    "websockets": "15.0.1"
  },
  "Optional Dependencies": {
    "anywidget": "0.9.18",
    "duckdb": "1.4.0",
    "nbformat": "5.10.4",
    "pandas": "2.3.2",
    "pyarrow": "21.0.0",
    "loro": "1.6.0"
  },
  "Experimental Flags": {}
}```

</details>


### Code to reproduce

https://gist.github.com/dvdkouril/27db97e757071abc1cf67c6b5f6ca718

### PR DESCRIPTION
**Pull request by manzt**
Fixes #6499 

The `msgspec` migration changed how we encode "buffers" (aka binary blobs) in the `UIElement.text`, causing our frontend to dual-encode the responses.

This commit properly decodes buffers at system boundaries by converting base64 strings to `DataView` objects at two key points:
- When extracting buffers from `SendUIElementMessage` operations in the WebSocket handler
- When resolving the initial value from HTML attributes in the AnyWidgetPlugin component

I added several tests were we missed these changes, verifying that buffers are correctly encoded as base64 in HTML and properly handled in the Python backend.

### CODE REVIEW

File: frontend/src/utils/data-views.ts [hunk 1]
```diff
@@ -1,16 +1,15 @@
 /* Copyright 2024 Marimo. All rights reserved. */
-import { get, set } from "lodash-es";
+import { set } from "lodash-es";
 import { invariant } from "./invariant";
-import { type Base64String, type ByteString, typedAtob } from "./json/base64";
 import { Logger } from "./Logger";
 
 /**
- * Update the object with DataView buffers at the specified paths.
+ * Update the ob etc with DataView buffers at the specified paths.
```
Comment (mscolnick) [inline frontend/src/utils/data-views.ts]:
```suggestion
 * Update the object with DataView buffers at the specified paths.
```

**Comment by manzt** [comment]
@mscolnick the frontend build popped up in another PR ... is that something with turbo? Also schema check failing just for the extra metadata (which i think is expected).
