### PR TITLE
mep/8: Setup cell protections

### LINKED ISSUE #4428: Setup cell runs twice in script mode
### Describe the bug

Once on setup, once on kernel run

### Environment

head

### Code to reproduce

_No response_

### PR DESCRIPTION
**Pull request by dmadisetti**
## 📝 Summary

Minor push for finishing off top level functions:

 - [x] Adds an error if setup cell has references

image

- [x] fixes #4428 and creates consistent script mode with setup only running once (best seen in tests/_runtime/test_single_execution.py) with tests/_runtime/script_data/script_global_setup_difference.py

### CODE REVIEW

**Review by mscolnick — DISMISSED** [review]
easy to add a few test cases for this?

**Comment by mscolnick** [comment]
sorry, seeing now it's still in draft

**Comment by dmadisetti** [comment]
Just wanted to break out certain parts before the static load PR gets too big

File: frontend/src/components/editor/output/MarimoErrorOutput.tsx [hunk 1]
```diff
@@ -147,6 +151,59 @@ export const MarimoErrorOutput = ({
...
+              )),
+            )}
+          </ul>
+          {cellId && <AutoFixButton errors={setupErrors} cellId={cellId} />}
+          <Tip
+            title="Why can't the setup cell have references?"
+            className="mb-2"
+          >
+            <p className="pb-2">
+              While the most cells can be in any order and contain any
```
Comment (mscolnick) [inline frontend/src/components/editor/output/MarimoErrorOutput.tsx:182]: "While most cells"

File: marimo/_ast/cell.py [hunk 2]
```diff
@@ -600,6 +600,12 @@ def add(mo, x, y):
         """
         assert self._app is not None
 
+        # Inject setup cell definitions so that We do not rerun the setup cell.
```
Comment (mscolnick) [inline marimo/_ast/cell.py:603]: nit: we

**Review by mscolnick — APPROVED** [review]
