### PR TITLE
fix keyboard shortcuts normalization

### LINKED ISSUE #8570: Changing Shift + Enter binding just results in new line
### Describe the bug

On my mac, I'd like to switch Shift + Enter and Cmd + Enter, but when I go to settings and swap the two, both shortcuts now simply enter a new line. If I replace Cmd + Enter with some random shortcut, Shift + Enter still enters a new line, so it's not swapping them that's an issue, it seems Shift + Enter only works if it's default

I tested the same thing on Linux and got the same results.

### Will you submit a PR?

- [ ] Yes

### Environment

<details>

```
{
  "marimo": "0.20.4",
  "editable": false,
  "location": "/Users/nickolai/.cache/uv/archive-v0/f6xu_-mc8hcB-pg04AJF5/lib/python3.13/site-packages/marimo",
  "OS": "Darwin",
  "OS Version": "23.5.0",
  "Processor": "arm",
  "Python Version": "3.13.2",
  "Locale": "C/en_US",
  "Binaries": {
    "Browser": "145.0.7632.159",
    "Node": "v23.7.0",
    "uv": "0.8.19"
  },
  "Dependencies": {
    "click": "8.3.1",
    "docutils": "0.22.4",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.10.2",
    "narwhals": "2.17.0",
    "packaging": "26.0",
    "psutil": "7.2.2",
    "pygments": "2.19.2",
    "pymdown-extensions": "10.21",
    "pyyaml": "6.0.3",
    "starlette": "0.52.1",
    "tomlkit": "0.14.0",
    "typing-extensions": "missing",
    "uvicorn": "0.41.0",
    "websockets": "16.0"
  },
  "Optional Dependencies": {
    "loro": "1.10.3"
  },
  "Experimental Flags": {}
}
```

</details>

### Code to reproduce

_No response_

### PR DESCRIPTION
**Pull request by Light2Dark**
## 📝 Summary

Fixes #8570.

The keyboard shortcuts settings dialog was lowercasing all key names (e.g., "Shift-enter" instead of "Shift-Enter"), causing CodeMirror to silently fail to match overridden bindings since its key lookup is case-sensitive

So, my config would look like this
```toml
[keymap.overrides]
"cell.run" = "Shift-enter"
"cell.runAndNewBelow" = "Cmd-enter"
```
Fixes:
- Added normalizeKeyString in the hotkey provider to capitalize multi-character base key names at read time, fixing both existing broken configs and manually edited ones
- Fixed the shortcut recording to preserve original casing for multi-character keys (Enter, Backspace, Tab, etc.) while still lowercasing single-character keys

## 📋 Checklist

- [x] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [ ] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [x] Tests have been added for the changes made.
- [ ] Documentation has been updated where applicable, including docstrings for API changes.
- [x] Pull request title is a good summary of the changes - it will be used in the [release notes](https://github.com/marimo-team/marimo/releases).

### CODE REVIEW

File: frontend/src/components/editor/controls/keyboard-shortcuts.tsx [hunk 1]
```diff
@@ -174,7 +174,9 @@ export const KeyboardShortcuts: React.FC = () => {
                 return;
               }
 
-              let key = e.key.toLowerCase();
+              // Single character keys are always lowercase (e.g. "a", "b", "c")
+              // But we should preserve the original case for other keys (e.g. "Enter", "Escape")
+              let key = e.key.length === 1 ? e.key.toLowerCase() : e.key;
```
Comment (Light2Dark) [inline frontend/src/components/editor/controls/keyboard-shortcuts.tsx:179]: Technically, this is the only fix that's needed. This would record keyboard shortcuts properly.

However, existing configs (broken ones) & manually entered configs will not work
