### PR TITLE
fix: copilot connection

### LINKED ISSUE #5364: GitHub Copilot not working in v0.14.0
### Describe the bug

Hey marimo team! 👋 

GitHub Copilot stopped working for me when going from 0.13.15 to 0.14.0, see attached gif.
It works perfectly as soon as I switch back to 0.13.15.

Image

### Will you submit a PR?

- [ ] Yes

### Environment

<details>

```
{
  "marimo": "0.14.0",
  "OS": "Linux",
  "OS Version": "6.8.0-1024-aws",
  "Processor": "x86_64",
  "Python Version": "3.13.3",
  "Binaries": {
    "Browser": "--",
    "Node": "v22.15.0"
  },
  "Dependencies": {
    "click": "8.2.1",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.8.2",
    "narwhals": "1.43.1",
    "packaging": "25.0",
    "psutil": "7.0.0",
    "pygments": "2.19.1",
    "pymdown-extensions": "10.15",
    "pyyaml": "6.0.2",
    "starlette": "0.47.0",
    "tomlkit": "0.13.3",
    "typing-extensions": "4.14.0",
    "uvicorn": "0.34.3",
    "websockets": "15.0.1"
  },
  "Optional Dependencies": {
    "altair": "5.5.0",
    "duckdb": "1.3.1",
    "nbformat": "5.10.4",
    "openai": "1.88.0",
    "polars": "1.31.0",
    "pyarrow": "20.0.0",
    "loro": "1.5.1",
    "ruff": "0.12.0",
    "sqlglot": "26.29.0"
  },
  "Experimental Flags": {}
}
```

</details>

### Code to reproduce

_No response_

### PR DESCRIPTION
**Pull request by akshayka**
The copilot language server's URL is just /copilot, no query parameters (such as the file) are used.

Without this change, we were attempting to connect to

/copilot?file=...

which would fail.

In previous releases, we first tried connecting to /copilot?file=..., which failed, but then we somehow connected to /copilot, which succeeded.

It seems like a recent change removed the second connection attempt, exposing this bug.

I've tested locally ... but in the future it would be good to have a better test for this.

Fixes #5364

### CODE REVIEW

File: frontend/src/core/runtime/runtime.ts [hunk 1]
```diff
@@ -104,6 +104,12 @@ export class RuntimeManager {
    * The URL of the copilot server.
    */
   getLSPURL(lsp: "pylsp" | "copilot"): URL {
+    if (lsp === "copilot") {
```
Comment (akshayka) [inline frontend/src/core/runtime/runtime.ts:107]: Connection logic is here: https://github.com/marimo-team/marimo/blob/6405da156e5ec39d454db38bdbc0b11e741e86b3/lsp/index.ts#L143-L154

**Review by manzt — APPROVED** [review]
Nice job tracking this down. Not totally sure how I'd test. I've been digging into our e2e stuff a bit and wonder if that could fit in there.
