### PR TITLE
generate different sql code based on dialect

### LINKED ISSUE #6875: Datasource "Add table to notebook" does not work for MS SQL
### Describe the bug

Marimo is using in the `Add table to notebook` function the SQL command `LIMIT`. This seems to be not available with MS SQL Servers.

I typically use 

```sql
SELECT TOP 100 * FROM SCHEMA.TABLENAME
```

instead of marimos default:
```sql
SELECT * FROM SCHEMA.TABLENAME LIMIT 100
```

### Will you submit a PR?

- [ ] Yes

### Environment

<details>

```
{
  "marimo": "0.17.0",
  "editable": false,
  "location": "OBFUSCATED/.venv/Lib/site-packages/marimo",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 140 Stepping 1, GenuineIntel",
  "Python Version": "3.13.8",
  "Binaries": {
    "Browser": "--",
    "Node": "v22.20.0"
  },
  "Dependencies": {
    "click": "8.3.0",
    "docutils": "0.22.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.9",
    "narwhals": "2.8.0",
    "packaging": "25.0",
    "psutil": "7.1.0",
    "pygments": "2.19.2",
    "pymdown-extensions": "10.16.1",
    "pyyaml": "6.0.3",
    "starlette": "0.48.0",
    "tomlkit": "0.13.3",
    "typing-extensions": "4.15.0",
    "uvicorn": "0.37.0",
    "websockets": "15.0.1"
  },
  "Optional Dependencies": {
    "altair": "5.5.0",
    "duckdb": "1.4.1",
    "nbformat": "5.10.4",
    "openai": "2.3.0",
    "pandas": "2.3.3",
    "polars": "1.34.0",
    "pyarrow": "21.0.0",
    "loro": "1.8.1",
    "pytest": "8.4.2",
    "python-lsp-server": "1.13.1",
    "ruff": "0.14.0",
    "sqlglot": "27.27.0"
  },
  "Experimental Flags": {
    "sql_linter": true
  }
}
```

</details>

### Code to reproduce

Add a MS SQL server connection, using `sqlalchemy`:

```python
import sqlalchemy as sa
engine = sa.create_engine(
    "mssql+pyodbc:{URL}?driver=ODBC+Driver+17+for+SQL+Server"
)
```

Then navigate to the datasources in marimo, choose any table for the engine above and click the plus button to `Add table to notebook`.

This will add a sql query to the notebook:

```python
_df = mo.sql(
    f"""
    SELECT * FROM SCHEMA.TABLENAME LIMIT 100
    """,
    engine=engine
)
```

### PR DESCRIPTION
**Pull request by Light2Dark**
## 📝 Summary

Fixes #6875. Might also tackle #6872.

## 📋 Checklist

- [x] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [ ] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [x] I have added tests for the changes made.
- [x] I have run the code and verified that it works as expected.

### CODE REVIEW

File: frontend/src/components/datasources/utils.ts [hunk 1]
```diff
@@ -9,6 +9,46 @@ export function isSchemaless(schemaName: string) {
...
+  // TimescaleDB: Wrap each part of qualified name with double quotes
+  timescaledb: {
+    formatTableName: (tableName: string) => {
+      const parts = tableName.split(".");
+      return parts.map((part) => `"${part}"`).join(".");
+    },
+    formatSelectClause: defaultFormatter.formatSelectClause,
+  },
+  default: defaultFormatter,
+};
```
Comment (mscolnick) [inline frontend/src/components/datasources/utils.ts]: i wonder if we can instead use `guessDialect` and the information from there for quoting

File: frontend/src/components/datasources/utils.ts [hunk 2]
```diff
@@ -39,11 +101,18 @@ export function sqlCode({
...
+      formattedTableName,
+    );
+
     if (engine === DUCKDB_ENGINE) {
-      return `_df = mo.sql(f"SELECT ${columnName} FROM ${tableName} LIMIT 100")`;
+      return `_df = mo.sql(f"""${selectClause}""")`;
     }
 
-    return `_df = mo.sql(f"SELECT ${columnName} FROM ${tableName} LIMIT 100", engine=${engine})`;
+    return `_df = mo.sql(f"""${selectClause}""", engine=${engine})`;
```
Comment (mscolnick) [inline frontend/src/components/datasources/utils.ts]: maybe new lines around the query in case it ends with a "

File: frontend/src/core/codemirror/language/languages/sql/utils.ts [hunk 3]
```diff
@@ -18,13 +18,49 @@ import {
...
  * Guess the CodeMirror SQL dialect from the backend connection dialect.
+ * If unknown, return the standard SQL dialect.
  */
 export function guessDialect(
   connection: Pick<DataSourceConnection, "dialect">,
-): SQLDialect | undefined {
-  switch (connection.dialect) {
+): SQLDialect {
+  const dialect = connection.dialect;
+  if (!isKnownDialect(dialect)) {
```
Comment (mscolnick) [inline frontend/src/core/codemirror/language/languages/sql/utils.ts:61]: would it better to just fall though the switch-case so this does not get out of sync?

**Review by mscolnick — COMMENTED** [review]
do we need the early returns for knowndialect? It seems like that could be error prone if we forget to add a case to the switch

**Comment by Light2Dark** [comment]
> do we need the early returns for knowndialect? It seems like that could be error prone if we forget to add a case to the switch

I can add a logNever and force us to return something. The reason to return early is to ensure the dialect is type-safe, so we must catch that dialect in the switch statements. It will throw error if spelling is off etc.

File: frontend/src/components/datasources/utils.ts (hunk 1 above)
Comment (Light2Dark) [reply frontend/src/components/datasources/utils.ts]: thanks for this, it only works for bigquery as some dialects from codemirror don't have identifierQuotes.
