### PR TITLE
fix: use mount_config.code and filename as fallback in WASM mode

### LINKED ISSUE #8026: `notebookFileStore` does not read `__MARIMO_MOUNT_CONFIG__.code`
### Describe the bug

When the html page for wasm contains no `<marimo-code>`, the fallback is the url arguments, then the local storage.

https://github.com/marimo-team/marimo/blob/718f80320a3bb2b316181dc5515e8d81683ed1fb/frontend/src/core/wasm/store.ts#L114

It does not take into account `mount_config.code`, which makes embedding marimo inside other contexts impossible (see also #7949). In my use-case, I fallback to the default marimo notebook, wihtout having any clue.

I think there might be another related problem:
On https://marimo.app, the "create permalink" button does not work. If I click on it and open the link in a private window, I get a different code (either a previous version or a notebook in my local storage). Maybe I am supposed to save beforehand, but when I click save I get `Failed to handle request: sendSave Error: Failed to fetch: `. If the error is unrelated, I will open a new issue.

### Will you submit a PR?

- [ ] Yes

### Environment

<details>

```
N/A (wasm)
```

</details>

### Code to reproduce

N/A

### PR DESCRIPTION
**Pull request by ffmiruz**
When embedding marimo in WASM mode without a marimo-code element, the mount config's code and filename options are now used as fallbacks.

Code fallback priority:
1. mount_config.code
2. marimo-code element
3. URL params
4. local storage
5. remote default
6. empty notebook

Filename fallback priority:
1. mount_config.filename
2. URL param (?filename=...)

Fixes #8026

### CODE REVIEW

**Comment by ffmiruz** [comment]
I have read the CLA Document and I hereby sign the CLA

File: frontend/src/core/wasm/store.ts [hunk 1]
```diff
@@ -67,6 +67,22 @@ const remoteDefaultFileStore: FileStore = {
...
+export function setMountConfigCode(code: string | null) {
+  mountConfigCode = code;
+}
+
+export const mountConfigFileStore: FileStore = {
+  saveFile(_contents: string) {
+    // Read-only: mount config code is set externally
+  },
+  readFile() {
+    return mountConfigCode;
```
Comment (mscolnick) [inline frontend/src/core/wasm/store.ts]: Maybe we can just read directly from the store here? And then can remove the `setMountConfig` function?

Comment (ffmiruz) [reply frontend/src/core/wasm/store.ts]: Done. Redo to not hold a copy of config code somewhere else.

File: frontend/src/core/wasm/store.ts [hunk 2]
```diff
@@ -118,8 +129,10 @@ export const notebookFileStore = new CompositeFileStore([
 ]);
 
 export const fallbackFileStore = new CompositeFileStore([
-  // Prefer then local storage, then remote default, then empty
+  // Prefer local storage (persists user edits), then mount config code,
+  // then remote default, then empty
   localStorageFileStore,
+  mountConfigFileStore,
```
Comment (mscolnick) [inline frontend/src/core/wasm/store.ts]: actually taking a step back, shouldn't this get picked up by `domElementFileStore` in `notebookFileStore`?

Comment (mscolnick) [reply frontend/src/core/wasm/store.ts]: oh, maybe mount config is being called without using `<marimo-code/>`?

do we want this to take precedence over local-storage? then maybe this should be in `notebookFileStore` (not a fallback)?

Comment (mscolnick) [reply frontend/src/core/wasm/store.ts]: it probably should go: 

1. `mountConfig` (because you make load a page once but mount a few times via naivation
2. `domElement` (one per page)
3. `url`

thoughts?

Comment (ffmiruz) [reply frontend/src/core/wasm/store.ts]: Hmm how i see it is, mount code is "init". And then if domELement is set, there is intention to override it. Same goes for url.
About localStorage, yea I'm a bit fuzzy. My thinking is, localStorage is to survive reload but if it always behind mount code then it is never useful, no? idk

But yea, mount code, domELement, url in some order inside notebookFileStore is probably the solution here.

Comment (mscolnick) [reply frontend/src/core/wasm/store.ts]: @ffmiruz, ping me when you make the change. i think we are on the same page

Comment (ffmiruz) [reply frontend/src/core/wasm/store.ts]: Can you confirm the order

Comment (mscolnick) [reply frontend/src/core/wasm/store.ts]: mount code, domELement, url in  notebookFileStore, seems correct to me.

Comment (ffmiruz) [reply frontend/src/core/wasm/store.ts]: Done
