### PR TITLE
fix: better chatbot input & bubble

### LINKED ISSUE #3401: support multiline for mo.ui.chat input & bubble
### Describe the bug

Image

1. The input textbox does not support multiple lines.
  Suggestion: make it an autosizing textarea. Some options:
  a) Add a new package - https://github.com/Andarist/react-textarea-autosize
  b) some css, js hack - https://css-tricks.com/auto-growing-inputs-textareas/#aa-other-ideas
  c) same behaviour as chat panel - but I think this isn't an option, that uses codemirror which is overkill.

     I tried and b) should work, avoids useLayoutEffect hooks from a)

2. Shift+enter / cmd+enter to add new line, Enter to submit.
   - This is a bit tricky since we need to override the code editor shortcut (shift+enter will go to the next cell)
   - One suggestion is we keep the default behaviour of textarea (Enter creates a new line), and we set `Ctrl+Enter` to submit the form

3. The chat bubble will auto format everything to 1 line.
    I believe there's a simple solution,`chat-ui.tsx`
    ```.tsx
      <p className={cn(message.role === "user" && "whitespace-pre-wrap")}>
        {renderMessage(message)}
      </p>
    ```

### Environment

<details>

```
{
  "marimo": "0.10.12",
  "OS": "Darwin",
  "OS Version": "23.6.0",
  "Processor": "arm",
  "Python Version": "3.12.8",
  "Binaries": {
    "Browser": "131.0.6778.265",
    "Node": "v23.2.0"
  },
  "Dependencies": {
    "click": "8.1.3",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.20.1",
    "packaging": "24.2",
    "psutil": "6.1.1",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.13",
    "pyyaml": "6.0.2",
    "ruff": "0.6.9",
    "starlette": "0.45.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.34.0",
    "websockets": "14.1"
  },
  "Optional Dependencies": {
    "anywidget": "0.9.13",
    "duckdb": "1.1.3",
    "ibis-framework": "9.5.0",
    "pandas": "2.2.3",
    "polars": "1.18.0",
    "pyarrow": "17.0.0"
  }
}
```

</details>

### Code to reproduce

```.py
mo.ui.chat(
  mo.ai.llm.openai(
    "gpt-4o-mini",
    system_message="You are a helpful chemist. Output your answer in markdown or latex.",
  ),
  show_configuration_controls=True,
)
```

### PR DESCRIPTION
**Pull request by Light2Dark**
## 📝 Summary

Screenshot 2025-01-13 at 1 24 50 AM

Fixes #3401 . Use codemirror as chatbot input,  `/` triggers autocomplete.

## 🔍 Description of Changes

- multiline input
- multiline chat bubble
- removed an unnecessary extension (codemirror-mentions) and implemented custom one
note: dataset atom is not finding any tables, hence `@` is not working.

## 📋 Checklist

- [X] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [ ] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [ ] I have added tests for the changes made.
- [X] I have run the code and verified that it works as expected.

## 📜 Reviewers

@akshayka OR @mscolnick

### CODE REVIEW

File: frontend/src/plugins/impl/chat/chat-ui.tsx [hunk 1]
```diff
@@ -309,22 +334,29 @@ export const Chatbot: React.FC<Props> = (props) => {
...
               });
             }}
           />
         )}
-        <input
-          name="prompt"
-          ref={inputRef}
+        <PromptInput
+          className="rounded-sm mr-2"
+          placeholder="Type your message here, / for prompts"
```
Comment (mscolnick) [inline frontend/src/plugins/impl/chat/chat-ui.tsx:345]: can we change the placeholder of prompts exist or not

File: frontend/src/components/editor/ai/add-cell-with-ai.tsx [hunk 2]
```diff
@@ -277,8 +283,17 @@ export const PromptInput = ({
       }),
     );
 
+    // Trigger autocompletion for text that begins with @ or
+    // @ + additional symbols specified
+    const matchBeforeRegex = additionalCompletions
```
Comment (mscolnick) [inline frontend/src/components/editor/ai/add-cell-with-ai.tsx:288]: Can we do 2 separate mentions plugins? One for "@" data and one for "/" prompts; instead of appending the trigger, replace it.

**Comment by mscolnick** [comment]
I think the mention changes are good / worth keeping. I plan to add support for MCPs so we could eventually replace this with https://github.com/marimo-team/codemirror-mcp

File: frontend/src/components/editor/ai/add-cell-with-ai.tsx (hunk 2 above)
Comment (Light2Dark) [reply frontend/src/components/editor/ai/add-cell-with-ai.tsx:288]: do you mean if there are `additionalCompletions`, we only use the "/" regex?

it's also possible to accept multiple regexes, if we want to make it extensible

```.tsx
export function mentions(
  matchBeforeRegexes: RegExp[],
  data: Completion[] = [],
): Extension {
  return autocompletion({
    override: [
      (context: CompletionContext) => {
        const word = matchBeforeRegexes
          .map((regex) => context.matchBefore(regex))
          .find(Boolean);
```

Comment (mscolnick) [reply frontend/src/components/editor/ai/add-cell-with-ai.tsx:290]: from the code, it looks like `@` would trigger autocomplete for prompts, and I was thinking that `@` only trigger autocomplete for datasets, while `/` triggers for prompts. you could maybe do this in a single `mentions` plugin, but doing two (one for datasets and one for prompts) might be easier

Comment (Light2Dark) [reply frontend/src/components/editor/ai/add-cell-with-ai.tsx]: hmm, you can't do 2 autocompletion extensions, since they will overwrite and cause a conflict from codemirror. Seems a solution will be tricky if we want to have 2 mentions plugin.

```.tsx
return [
      mentions(/@(\w+)?/, completions),
      mentions(/\/(\w+)?/, additionalCompletions?.completions),
      ...
]
```
error: Config merge conflict for field override

but anyways, `@` will indeed trigger autocomplete, but there are no matching prompts beginning with `@`, so nothing is found.

Comment (mscolnick) [reply frontend/src/components/editor/ai/add-cell-with-ai.tsx]: gotcha. i see, that makes sense. 

then what you have is good to me.

**Review by mscolnick — APPROVED** [review]
awesome stuff!
