### PR TITLE
Make reactivity options in footer responsive for small screen widths

### LINKED ISSUE #5495: Bottom toolbar overflows for small width displays
### Describe the bug

When the window is resized to a small width, UI elements in the bottom toolbar overlap and the text becomes awkwardly arranged (e.g., "on startup:", "on cell change:").

Image

**Idea**: Hide non-essential text or group the [on startup, on cell change, on module change] into an icon with expandable UI when on smaller breakpoints.

### Will you submit a PR?

- [ ] Yes

### Environment

<details>

```
Replace this line with the output of marimo env. Leave the backticks in place.
```

</details>

### Code to reproduce

_No response_

### PR DESCRIPTION
**Pull request by manzt**
Fixes #5495

Fixes bottom toolbar overflow issue on small displays by implementing
responsive design that groups runtime settings into a settings dropdown.
When screen width is below `md` (768px), the footer shows a settings icon
instead of individual runtime controls, preventing text overlap.

https://github.com/user-attachments/assets/805819de-a8b8-4d9e-8ef0-b6c26a72961b

### CODE REVIEW

File: frontend/src/components/editor/chrome/wrapper/footer-items/runtime-settings.tsx [hunk 1]
```diff
@@ -0,0 +1,346 @@
...
+    await saveUserConfig({ config: newUserConfig }).then(() =>
+      setUserConfig(newUserConfig),
+    );
+  };
+
+  // Check if all reactivity is disabled
+  const allReactivityDisabled =
+    !config.runtime.auto_instantiate &&
+    config.runtime.on_cell_change === "lazy" &&
+    (isWasm() || config.runtime.auto_reload !== "autorun");
```
Comment (manzt) [inline frontend/src/components/editor/chrome/wrapper/footer-items/runtime-settings.tsx:98]: The icon will show with strikethrough if all are disabled... and active if any of the settings are enabled.
