### PR TITLE
fix: show elapsed time for errored cells

### LINKED ISSUE #458: Marimo doesn't show how long a cell was running for if it errors out
### Describe the bug

If a cell errors out, there is no way to tell how long it was running for (whereas all other cells display runtime)

### Environment

{
  "marimo": "0.1.65",
  "OS": "Darwin",
  "OS Version": "22.6.0",
  "Processor": "arm",
  "Python Version": "3.11.4",
  "Binaries": {
    "Chrome": "120.0.6099.71",
    "Node": "v20.3.1"
  },
  "Requirements": {
    "black": "23.10.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.3.1",
    "tomlkit": "0.12.1",
    "tornado": "6.3.3",
    "typing_extensions": "4.8.0"
  }
}

### Code to reproduce

```
import time
time.sleep(5)
raise ValueError()
```

### PR DESCRIPTION
**Pull request by akshayka**
This change fixes an issue in which the elapsed time wasn't shown for errored cells.

Closes #458.

### CODE REVIEW

File: frontend/src/core/cells/cell.ts [hunk 1]
```diff
@@ -65,18 +66,9 @@ export function transitionCell(
       // The cell didn't run, but it was intentional, so don't count as
       // errored.
       nextCell.stopped = true;
-      // Update elapsed time, since it is still useful to know how long before
-      // the cell was stopped.
```
Comment (akshayka) [inline frontend/src/core/cells/cell.ts:69]: If an ancestor was stopped, then the cell didn't run at all

File: frontend/src/core/cells/cell.ts [hunk 2]
```diff
@@ -65,18 +66,9 @@ export function transitionCell(
...
-        ? (message.timestamp - cell.runStartTimestamp) * 1000
-        : null;
     } else {
+      // Communicate that the cell errored (e.g., an exception was raised)
       nextCell.errored = true;
-      // Update elapsed time, since it is still useful to know how long before
-      // the cell was stopped.
-      nextCell.runElapsedTimeMs = cell.runStartTimestamp
-        ? (message.timestamp - cell.runStartTimestamp) * 1000
-        : null;
```
Comment (akshayka) [inline frontend/src/core/cells/cell.ts:79]: @mscolnick this was the fix, this is already calculated in the switch statement on message status, when an `idle` message is sent

**Review by mscolnick — APPROVED** [review]
