### PR TITLE
fix: LSP reconfiguration missing cell-id

### LINKED ISSUE #7993: language server(s) and autocompletion show inconsistent behavior
### Describe the bug

Tried all possible configurations of language servers:  ty, Python Language Server and None.
The autocompletion and documentation tab show inconsistent behavior. 
It is possible that language3 server configurations need kernel restart everytime, not exactly tested yet

# Function autocomplete
## Case 1, ty works as intended
Image

## Case 2, ty, start writing arguments Documentation tab lost context

Image

## Case 3, any language server, randomly lost helper tooltip and couldn't get it back

Image

## Case 4, single function, any language server, did not get tooltip

Image

# Dataclass autocomplete
## Case 1, language server are active (ty and python), works 

Image

## Case 2, language server are deactivated, works "better" as it gives what the user possibly need

Image

## Case 3, language server are activated again (without resetting kernel or anything), nothing works

Image

### Will you submit a PR?

- [ ] Yes

### Environment

<details>

```
{
  "marimo": "0.19.6",
  "editable": false,
  "location": "/Users/mixpap/projects/astro/NGC6328_jax/.venv/lib/python3.13/site-packages/marimo",
  "OS": "Darwin",
  "OS Version": "25.2.0",
  "Processor": "arm",
  "Python Version": "3.13.2",
  "Locale": "en_US",
  "Binaries": {
    "Browser": "--",
    "Node": "v23.10.0"
  },
  "Dependencies": {
    "click": "8.3.1",
    "docutils": "0.22.4",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.10.1",
    "narwhals": "2.15.0",
    "packaging": "25.0",
    "psutil": "7.2.1",
    "pygments": "2.19.2",
    "pymdown-extensions": "10.20.1",
    "pyyaml": "6.0.3",
    "starlette": "0.50.0",
    "tomlkit": "0.14.0",
    "typing-extensions": "4.15.0",
    "uvicorn": "0.40.0",
    "websockets": "15.0.1"
  },
  "Optional Dependencies": {
    "anywidget": "0.9.21",
    "loro": "1.10.3",
    "mcp": "1.26.0",
    "nbformat": "5.10.4",
    "openai": "2.15.0",
    "pandas": "3.0.0",
    "polars": "1.37.1",
    "pyarrow": "23.0.0",
    "python-lsp-ruff": "2.3.0",
    "python-lsp-server": "1.14.0",
    "ruff": "0.14.14",
    "ty": "0.0.13"
  },
  "Experimental Flags": {
    "chat_modes": true,
    "inline_ai_tooltip": true,
    "external_agents": true
  }
}
```

</details>

### Code to reproduce

_No response_

### PR DESCRIPTION
**Pull request by mscolnick**
Fixes #7993

When changing (adding or removing) LSPs, it would cause a Reconfigure of the extensions, which would lose the `CellId` from the facet. This makes sure it is there.

### CODE REVIEW

File: frontend/src/core/codemirror/facet.ts [hunk 1]
```diff
@@ -14,6 +14,9 @@ import { Facet } from "@codemirror/state";
  */
 export function singleFacet<T>() {
   return Facet.define<T, T>({
-    combine: (values) => values[0],
+    combine: (values) => {
+      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+      return values.find((v) => v !== undefined)!;
+    },
```
Comment (Light2Dark) [inline frontend/src/core/codemirror/facet.ts:20]: should throw if all are undefined? or to satisfy typechecker at least
```suggestion
      const value = values.find((v) => v !== undefined);
      if (value === undefined) {
        throw new Error("singleFacet: no value provided");
      }
      return value;
```

Comment (Light2Dark) [reply frontend/src/core/codemirror/facet.ts:20]: or
```suggestion
    combine: (values) => {
      return values.find((v) => v !== undefined) ?? values[0];
    },
```

**Review by Light2Dark — APPROVED** [review]
