### PR TITLE
fix: --base-url breaks og:thumbnail generation path (marimo-team#8304)

### LINKED ISSUE #8304: --base-url breaks og:thumbnail generation path
### Describe the bug

When using --base-url for run/edit command, thumbnails do not work.
I think the relative path should be provided in asURL argument. 

https://github.com/marimo-team/marimo/blob/b58b6786258241856132800c13c2e3d0ef2e3fd2/frontend/src/components/pages/gallery-page.tsx#L71-L76

    uv run marimo run notebooks/ --watch --base-url /test

Image

### Will you submit a PR?

- [x] Yes

### Environment

<details>

```
{
  "marimo": "0.19.11",
  "editable": false,
  "location": "/Users/me/marimo/.venv/lib/python3.12/site-packages/marimo",
  "OS": "Darwin",
  "OS Version": "25.2.0",
  "Processor": "arm",
  "Python Version": "3.12.12",
  "Locale": "--",
  "Binaries": {
    "Browser": "144.0.7559.133",
    "Node": "v25.3.0",
    "uv": "0.10.0 (Homebrew 2026-02-05)"
  },
  "Dependencies": {
    "click": "8.3.1",
    "docutils": "0.22.4",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.10",
    "narwhals": "2.15.0",
    "packaging": "25.0",
    "psutil": "7.2.1",
    "pygments": "2.19.2",
    "pymdown-extensions": "10.20",
    "pyyaml": "6.0.3",
    "starlette": "0.52.1",
    "tomlkit": "0.14.0",
    "typing-extensions": "4.15.0",
    "uvicorn": "0.40.0",
    "websockets": "16.0"
  },
  "Optional Dependencies": {
    "altair": "6.0.0",
    "duckdb": "1.4.3",
    "loro": "1.10.3",
    "mcp": "1.26.0",
    "nbformat": "5.10.4",
    "openai": "2.15.0",
    "pandas": "2.3.3",
    "polars": "1.37.1",
    "pyarrow": "23.0.0",
    "pytest": "9.0.2",
    "python-lsp-ruff": "2.3.0",
    "python-lsp-server": "1.14.0",
    "ruff": "0.14.13",
    "sqlglot": "28.6.0",
    "vegafusion": "2.0.3"
  },
  "Experimental Flags": {}
}
```

</details>

### Code to reproduce

_No response_

### PR DESCRIPTION
**Pull request by mstanowski**
## 📝 Summary

On a gallery page, the default card thumbnail was using an absolute /og/thumbnail path, which breaks thumbnail generation when the --base-url option is used in run mode.

Closes #8304

## 🔍 Test Plan
- Open marimo in run mode, providing a directory and the --base-url argument.
- Verify that there are no missing default thumbnails for notebooks.

### CODE REVIEW

**Comment by mstanowski** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by mscolnick — APPROVED** [review]

File: frontend/src/components/pages/gallery-page.tsx [hunk 1]
```diff
@@ -72,7 +72,7 @@ const GalleryPage: React.FC = () => {
           opengraphImage && isHttpsUrl(opengraphImage)
             ? opengraphImage
             : asURL(
-                `/og/thumbnail?file=${encodeURIComponent(relativePath)}`,
+                `og/thumbnail?file=${encodeURIComponent(relativePath)}`,
```
Comment (peter-gy) [inline frontend/src/components/pages/gallery-page.tsx:75]: great catch @mstanowski, thank you!
