### PR TITLE
experimental: tracing panel

### LINKED ISSUE #2898: Display cell run history
### Description

I'm working with a large dataset and occasionally running into OOM errors. When the process is killed, there no way on the frontend to determine the last run cell (or cell that was running before OOM)

### Suggested solution

Image

 - Clicking the broken link scrolls to the last cell
 - Some styling on the broken cell (just the red error might be fine)

### Alternative

_No response_

### Additional context

Happy to put this in myself, just leaving a bookmark. Small QOL improvement

### PR DESCRIPTION
**Pull request by Light2Dark**
## 📝 Summary

Fixes #2898. A v1 tracing panel for observability efforts

https://github.com/user-attachments/assets/1c042e0b-2f70-4ec0-ad63-a0c59d5a89a4

## 🔍 Description of Changes

- view cell runs, status, code snippet and timestamps
- hover sync between react components and vega chart
- supports dark theme
- each run now has a run_id context from the backend
- note: the timestamps here should be 'more accurate' than the frontend timers since they come from code execution in the backend. Hence, there can also be a small discrepancy btwn them.

## 📋 Checklist

- [X] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [X] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [X] I have added tests for the changes made.
- [X] I have run the code and verified that it works as expected.

## 📜 Reviewers

@akshayka OR @mscolnick

### CODE REVIEW

File: frontend/src/components/tracing/tracing.tsx [hunk 1]
```diff
@@ -0,0 +1,391 @@
...
+);
+
+interface CellRun {
+  cellID: string;
+  code: string;
+  elapsedTime: number;
+  status: RunStatus;
+}
+
+export interface Run {
```
Comment (mscolnick) [inline frontend/src/components/tracing/tracing.tsx:22]: Do you want me to connect this to the backend? i get the backend to return a runId for each cell-op, and get you setup so you can pull this data from state

Comment (Light2Dark) [reply frontend/src/components/tracing/tracing.tsx:22]: yeah! hmm, I thought it would be more complex but that should work. I'm happy to try connecting it myself 🤔 unless you foresee difficult challenges or decisions.

**Comment by mscolnick** [comment]
i can't figure out how to contribute back to your repo, but you can cherry-pick this commit: 1f58e530fc7be5637dde5b856893f269ce9c24db

File: openapi/README.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+# Modifying the API Specification
```
Comment (mscolnick) [inline openapi/README.md:1]: this exists in development docs too. maybe we could consolidate (if needed)

Comment (Light2Dark) [reply openapi/README.md:1]: oh wow, didn't know this existed. Rest of the PR still needs work, will get to it soon!

File: marimo/_runtime/runtime.py [hunk 3]
```diff
@@ -1136,18 +1137,19 @@ def mutate_graph(
...
-        # common cases. We could also be more aggressive and run this before
-        # every cell, or even before pickle.dump/pickle.dumps()
-        with patches.patch_main_module_context(self._module):
-            while cell_ids := await self._run_cells_internal(cell_ids):
-                LOGGER.debug("Running state updates ...")
-                if self.lazy() and cell_ids:
-                    self.graph.set_stale(cell_ids, prune_imports=True)
-                    break
-            LOGGER.debug("Finished run.")
+        with run_id_context():
```
Comment (Light2Dark) [inline marimo/_runtime/runtime.py:1140]: Curious why you decided to use a context manager to get run_id rather than pass a parameter to the function. I can see that it could bloat the function definitions.

Comment (mscolnick) [reply marimo/_runtime/runtime.py:1140]: i usually prefer args over this sideways injection. but there is a lot of layers that would need changes to pass this down. if context becomes buggy or hard to test, we can move to args later

**Comment by Light2Dark** [comment]
feel free to review! I'm thinking of how to add more backend tests, and a new icon for the 'queued' state, have reached out to @wasimsandhu for reference on that :)

File: frontend/src/components/tracing/tracing.tsx [hunk 4]
```diff
@@ -0,0 +1,325 @@
...
+      <span className="w-40 truncate">{cellRun.code}</span>
+
+      <div className="flex flex-row gap-1 basis-12 justify-end">
+        <Tooltip content={elapsedTimeTooltip}>
+          <span className="text-[var(--gray-10)]">{elapsedTimeStr}</span>
+        </Tooltip>
+
+        {/* TODO: Shouldn't use favicon and need to add an image for 'queued' state. */}
+        <Tooltip content={cellRun.status}>
+          <img
```
Comment (mscolnick) [inline frontend/src/components/tracing/tracing.tsx:295]: if you don't get one, it could be ok to use colors and lucid icons:

Queued: https://lucide.dev/icons/loader (gray)
Running: https://lucide.dev/icons/loader-circle + `animate-spine` (darker-gray)
Done: https://lucide.dev/icons/circle-check (green)
Failed: https://lucide.dev/icons/circle-x (red)

File: frontend/src/core/cells/__tests__/runs.test.ts [hunk 5]
```diff
@@ -0,0 +1,321 @@
...
+          timestamp: timestamp + 2000,
+          status: "queued",
+        },
+        code: "console.log('Run 3');",
+      },
+    });
+
+    expect(finalState.runIds).toEqual([runId3, runId2, runId]);
+  });
+});
```
Comment (mscolnick) [inline frontend/src/core/cells/__tests__/runs.test.ts:321]: 🚀

File: marimo/_messaging/ops.py [hunk 6]
```diff
@@ -127,8 +129,25 @@ class CellOp(Op):
...
+        try:
+            # run_id context is only set during a run
+            if self.status is not None:
+                self.run_id = RUN_ID_CTX.get()
+        except LookupError:
+            # Be specific about the exception we're catching
+            # The context variable hasn't been set yet
+            # TODO: where are these warnings coming from?
+            # good enough to silence for now?
+            LOGGER.warning("No run_id context found, setting to None")
```
Comment (mscolnick) [inline marimo/_messaging/ops.py:145]: i assume this warning is still in a lot of places. we can just remove this line and the TODO if things are working as expected

File: frontend/src/components/tracing/tracing-spec.ts [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+  if (hideYAxisLine) {
+    yAxis.axis = null;
+  }
+
+  return {
+    $schema: "https://vega.github.io/schema/vega-lite/v5.json",
+    mark: {
+      type: "bar",
+      cornerRadius: 2,
+      fill: "#37BE5F", // same colour as chrome's network tab
```
Comment (mscolnick) [inline frontend/src/components/tracing/tracing-spec.ts:41]: does this work in dark mode?

**Review by mscolnick — COMMENTED** [review]
THIS IS SO COOL

**Comment by mscolnick** [comment]
The backend changes are minimal so don't need to add to many tests. maybe just one or two:

(unsure if this passes / compiles
```python
    async def test_has_run_id(
        self, mocked_kernel: MockedKernel, exec_req: ExecReqProvider
    ) -> None:
        k = mocked_kernel.k
        await k.run(
            [exec_req.get("print('foo'"),]
        )
        cell_ops = run_mode_kernel.stream.cell_ops
        assert len(cell_ops) == 1
        assert cell_ops[0]["run_id"] is not None
```

File: frontend/src/components/tracing/tracing-spec.ts (hunk 7 above)
Comment (Light2Dark) [reply frontend/src/components/tracing/tracing-spec.ts]: added support dark charts

File: frontend/src/components/tracing/tracing.tsx (hunk 4 above)
Comment (Light2Dark) [reply frontend/src/components/tracing/tracing.tsx]: I'm opting to use ellipsis for queued to maintain design consistency with the editor. But let me know if you prefer a loader.

File: tests/_runtime/test_runtime.py [hunk 8]
```diff
@@ -1227,6 +1227,22 @@ async def test_temporaries_deleted(
         await k.run([ExecutionRequest(er.cell_id, "None")])
         assert f"_cell_{er.cell_id}_x" not in k.globals
 
+    async def test_has_run_id(
```
Comment (Light2Dark) [inline tests/_runtime/test_runtime.py:1230]: I'm not sure why this test fails, `mocked_kernel.stream.messages` does contain run_id but`parse_raw` doesn't create a class with run_id.

**Comment by Light2Dark** [comment]
:)) just the backend test left.

File: tests/_runtime/test_runtime.py (hunk 8 above)
Comment (mscolnick) [reply tests/_runtime/test_runtime.py:1230]: oh i accidentlly gave you a bug. it's trying to post-init again, 

```diff
    def __post_init__(self) -> None:
+      if self.run_id is not None:
+           return
        try:
            self.run_id = RUN_ID_CTX.get()
        except LookupError:
            # Be specific about the exception we're catching
            # The context variable hasn't been set yet
            # may want to explore why this is happening in the future
            self.run_id = None
        except Exception as e:
            LOGGER.error("Error getting run id: %s", str(e))
            self.run_id = None
```

**Review by mscolnick — APPROVED** [review]
sick, this is amazing! ⚡

File: frontend/src/components/tracing/tracing.tsx [hunk 9]
```diff
@@ -0,0 +1,348 @@
...
+
+const Chart: React.FC<ChartProps> = (props: ChartProps) => {
+  return (
+    <div className={props.className}>
+      <LazyVega
+        spec={props.vegaSpec}
+        theme={props.theme === "dark" ? "dark" : undefined}
+        width={props.width}
+        height={props.height}
+        signalListeners={props.signalListeners}
```
Comment (mscolnick) [inline frontend/src/components/tracing/tracing.tsx:123]: i think `actions={false}` would look better

File: tests/_runtime/test_runtime.py (hunk 8 above)
Comment (Light2Dark) [reply tests/_runtime/test_runtime.py:1230]: interesting..oh wait, yes I remember why this doesn't work. If you refresh the page, empty runs are created.

Comment (Light2Dark) [reply tests/_runtime/test_runtime.py:1230]: okiee have a fix

Comment (Light2Dark) [reply tests/_runtime/test_runtime.py:1230]: thanks for all the suggestions & backend work! I think dark theme was a good addition too

**Review by mscolnick — APPROVED** [review]
AMAZING WORK!
