### PR TITLE
fix: hide invalid options on setup cell context menu

### LINKED ISSUE #5965: setup cell can be renamed, disabled and have other invalid operations occur
### Describe the bug

Renaming the setup cell in the editor gets things into a weird state, there are a few other options we should hide from the context menu:

Image

### Will you submit a PR?

- [ ] Yes

### Environment

Head: https://marimo.app/l/gocsfh

### Code to reproduce

_No response_

### PR DESCRIPTION
**Pull request by dmadisetti**
## 📝 Summary

Closes #5965 

image

Removes actions on setup cell that are invalid (like cell movement)

### CODE REVIEW

File: frontend/src/components/editor/actions/useCellActionButton.tsx [hunk 1]
```diff
@@ -136,6 +136,8 @@ export function useCellActionButtons({ cell, closePopover }: Props) {
     }
   };
 
+  const isSetupCell = cellId === "setup";
```
Comment (mscolnick) [inline frontend/src/components/editor/actions/useCellActionButton.tsx]: Is there a constant we can grab this from?

**Review by mscolnick — DISMISSED** [review]

File: frontend/src/components/editor/actions/useCellActionButton.tsx [hunk 2]
```diff
@@ -377,13 +392,15 @@ export function useCellActionButtons({ cell, closePopover }: Props) {
...
         handle: () => sendToBottom({ cellId, scroll: false }),
+        hidden: isSetupCell,
       },
       {
         icon: <Columns2Icon size={13} strokeWidth={1.5} />,
         label: "Break into new column",
         hotkey: "cell.addColumnBreakpoint",
         hidden: appWidth !== "columns",
         handle: () => addColumnBreakpoint({ cellId }),
+        hidden: isSetupCell,
```
Comment (mscolnick) [inline frontend/src/components/editor/actions/useCellActionButton.tsx]: there is a bug with this one

Comment (dmadisetti) [reply frontend/src/components/editor/actions/useCellActionButton.tsx]: Ah, thanks
