### PR TITLE
fix: add mathjax ignore so code does not get malformed

### LINKED ISSUE #4579: Marimo + Plotly corrupts notebook cell
### Describe the bug

Opening this marimo notebook causes the cell to become corrupted.

Before:
```python
import plotly.graph_objects as go

# mo.md(f"```\n{foo=!r}\n{bar=!r}\n```"),
go.Figure()
```

After:
```python
import plotly.graph_objects as go

# mo.md(f"n{f∞=!r}n{ˉ=!r}n\n{foo=!r}\n{bar=!r}\n"),
go.Figure()
```

### Environment

<details>

```
{
  "marimo": "0.12.10",
  "OS": "Darwin",
  "OS Version": "23.6.0",
  "Processor": "arm",
  "Python Version": "3.11.10",
  "Binaries": {
    "Browser": "--",
    "Node": "v22.14.0"
  },
  "Dependencies": {
    "click": "8.1.8",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.8",
    "narwhals": "1.35.0",
    "packaging": "24.2",
    "psutil": "7.0.0",
    "pygments": "2.19.1",
    "pymdown-extensions": "10.14.3",
    "pyyaml": "6.0.2",
    "starlette": "0.46.2",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.13.2",
    "uvicorn": "0.34.1",
    "websockets": "15.0.1"
  },
  "Optional Dependencies": {
    "altair": "5.5.0",
    "duckdb": "1.2.2",
    "nbformat": "5.10.4",
    "openai": "1.75.0",
    "pandas": "2.2.3",
    "polars": "1.27.1",
    "pyarrow": "19.0.1",
    "pycrdt": "0.11.1",
    "ruff": "0.11.6",
    "sqlglot": "26.15.0"
  },
  "Experimental Flags": {}
}
```

</details>

### Code to reproduce

```python
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "marimo",
#     "plotly==6.0.1",
# ]
# ///

import marimo

__generated_with = "0.12.10"
app = marimo.App()


@app.cell
def _():
    import plotly.graph_objects as go

    # mo.md(f"```\n{foo=!r}\n{bar=!r}\n```"),
    go.Figure()
    return (go,)


if __name__ == "__main__":
    app.run()
```

### PR DESCRIPTION
**Pull request by mscolnick**
Fixes #4579

### CODE REVIEW

File: frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx [hunk 1]
```diff
@@ -112,7 +112,7 @@ export const PlotlyComponent = memo(
 
     // Used for rendering LaTeX. TODO: Serve this library from Marimo
     const scriptStatus = useScript(
-      "https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-MML-AM_CHTML",
+      "https://cdn.jsdelivr.net/npm/mathjax-full@3.2.2/es5/tex-mml-svg.min.js",
```
Comment (Light2Dark) [inline frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx:115]: do you think we should use https://cdn.jsdelivr.net/npm/mathjax-full@latest/es5/tex-mml-svg.min.js. I checked with diffchecker, looks the exact same.

Comment (Light2Dark) [inline frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx:115]: wonder if we can use the latest https://cdn.jsdelivr.net/npm/mathjax-full@3.2.2/es5/tex-mml-svg.min.js . I used diffchecker, seems the same.

Comment (mscolnick) [reply frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx:115]: `3.2.2` is currently the`latest`. but pinning to "latest" could lead to breaking changes that we are unaware of

Comment (Light2Dark) [reply frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx:115]: alright :>

**Review by Light2Dark — APPROVED** [review]
