### PR TITLE
fix: select all on a searched table

### LINKED ISSUE #3970: Select all table rows doesn't select all on filtered table.
### Describe the bug

* Create a `mo.ui.table` from a dataframe
* Filter to a subset of the rows using search
* Select all rows from the top right, then click select all again
* Only a subset of rows are shown to be selected, but all of them should be selected.

See screencast

https://github.com/user-attachments/assets/6a498a71-0d69-45f9-9fab-253c02375980

### Environment

<details>

```
{
  "marimo": "0.11.14",
  "OS": "Darwin",
  "OS Version": "22.5.0",
  "Processor": "arm",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "133.0.6943.142",
    "Node": "v21.5.0"
  },
  "Dependencies": {
    "click": "8.1.8",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.29.0",
    "packaging": "24.2",
    "psutil": "7.0.0",
    "pygments": "2.19.1",
    "pymdown-extensions": "10.14.3",
    "pyyaml": "6.0.2",
    "ruff": "0.9.9",
    "starlette": "0.46.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.34.0",
    "websockets": "15.0"
  },
  "Optional Dependencies": {},
  "Experimental Flags": {
    "reactive_tests": true,
    "rtc": false,
    "multi_column": true,
    "chat_sidebar": true,
    "inline_ai_tooltip": true
  }
}
```

</details>

### Code to reproduce

```python
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "marimo",
#     "vega-datasets==0.9.0",
# ]
# ///

import marimo

__generated_with = "0.11.14"
app = marimo.App(width="medium")


@app.cell
def _():
    from vega_datasets import data
    return (data,)


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell
def _(data, mo):
    df = mo.ui.table(data.cars())
    df
    return (df,)


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
```

### PR DESCRIPTION
**Pull request by Light2Dark**
## 📝 Summary

Fixes #3970. A little bit rough, this adds a backend function to get all row_ids. Prevents search with select all for very large datasets.

## 📋 Checklist

- [X] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [ ] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [X] I have added tests for the changes made.
- [X] I have run the code and verified that it works as expected.

## 📜 Reviewers

@akshayka OR @mscolnick

### CODE REVIEW

File: frontend/src/plugins/impl/DataTablePlugin.tsx [hunk 1]
```diff
@@ -81,7 +87,7 @@ interface Data<T> {
 }
 
 // eslint-disable-next-line @typescript-eslint/consistent-type-definitions
-type Functions = {
+type DataTableFunctions = {
```
Comment (Light2Dark) [inline frontend/src/plugins/impl/DataTablePlugin.tsx:90]: small refactor: changed the name because it clashes with a prior imported util.

**Review by mscolnick — APPROVED** [review]
looks great. and great approach.
