### PR TITLE
fix: prevent sidebar resize handle from overlapping file explorer buttons  

### LINKED ISSUE #5920: Resizing of window interferes with renaming files button
### Describe the bug

The resizing window overlaps with the button to rename a file. It's not a major bug, only a minor inconvenience. Will  attempt to fix but would assume longer timeline as I'm quite busy with work. 

Image

### Will you submit a PR?

- [x] Yes

### Environment

<details>

```
{
  "marimo": "0.14.16",
  "editable": false,
  "OS": "Linux",
  "OS Version": "6.6.87.2-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.12.3",
  "Binaries": {
    "Browser": "--",
    "Node": "v22.17.0"
  },
  "Dependencies": {
    "click": "8.2.1",
    "docutils": "0.22",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.8.2",
    "narwhals": "2.0.1",
    "packaging": "25.0",
    "psutil": "7.0.0",
    "pygments": "2.19.2",
    "pymdown-extensions": "10.16.1",
    "pyyaml": "6.0.2",
    "starlette": "0.47.2",
    "tomlkit": "0.13.3",
    "typing-extensions": "4.14.1",
    "uvicorn": "0.35.0",
    "websockets": "15.0.1"
  },
  "Optional Dependencies": {
    "pandas": "2.3.1",
    "loro": "1.5.3",
    "ruff": "0.12.7"
  },
  "Experimental Flags": {}
}
```

</details>

### Code to reproduce

N/A

### PR DESCRIPTION
**Pull request by maxkoretskyi**
## 📝 Summary

Closes #5920

## Description of Changes

The sidebar resize handle's hit area overlapped with the file explorer's three-dot menu button, making it difficult to click "Rename" and other file actions.

Two changes in `frontend/src/components/editor/chrome/wrapper/app-chrome.tsx`:

1. **Removed `mr-[-4px]` negative margin** on the sidebar panel body. This margin was pushing the file list content 4px into the resize handle zone, causing the entire handle to sit on top of interactive elements.

2. **Reduced `hitAreaMargins` on `PanelResizeHandle`** from the library default of `{ coarse: 15, fine: 5 }` to `{ coarse: 15, fine: 2 }`. The `fine` value controls the invisible hit area for mouse pointers — reducing it from 5px to 2px keeps the resize cursor from appearing too far from the actual panel edge. The `coarse` value (touch devices) is kept at the default since larger touch targets are needed there.

## Checklist

- [x] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [ ] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [ ] Tests have been added for the changes made.
- [ ] Documentation has been updated where applicable, including docstrings for API changes.
- [x] Pull request title is a good summary of the changes - it will be used in the [release notes](https://github.com/marimo-team/marimo/releases).

### CODE REVIEW

File: frontend/src/components/editor/chrome/wrapper/app-chrome.tsx [hunk 1]
```diff
@@ -281,7 +282,7 @@ export const AppChrome: React.FC<PropsWithChildren> = ({ children }) => {
   const helpPaneBody = (
     <ErrorBoundary>
       <PanelSectionProvider value="sidebar">
-        <div className="flex flex-col h-full flex-1 overflow-hidden mr-[-4px]">
```
Comment (Light2Dark) [inline frontend/src/components/editor/chrome/wrapper/app-chrome.tsx:284]: I believe the margin was added because there is some whitespace if not

Image

Comment (maxkoretskyi) [reply frontend/src/components/editor/chrome/wrapper/app-chrome.tsx:284]: yeah, true, but visually it doesn't look bad, do you think we should still try to play with a DOM/CSS structure to try to come up with a better visual solution?

Comment (maxkoretskyi) [reply frontend/src/components/editor/chrome/wrapper/app-chrome.tsx:284]: > Is the hitAreaMargins sufficient? If not we can push the buttons further in imo.

yeah, I tested it, for me 2px worked fine, but that was with removed negative margin

Comment (Light2Dark) [reply frontend/src/components/editor/chrome/wrapper/app-chrome.tsx:284]: > > Is the hitAreaMargins sufficient? If not we can push the buttons further in imo.
> 
> yeah, I tested it, for me 2px worked fine, but that was with removed negative margin

yeah, I think we can try different options if possible, since it affects other panels too. We've reverted the margin change for now.
