### PR TITLE
fix: dont hide cell if interactive with vim search or dropdowns

### LINKED ISSUE #2594: Cells with "Hide code" enabled hides as soon as "Open cell actions" is clicked
### Describe the bug

If I have a cell code with "Hide code" enabled, it is hidden as soon as I click "Open cell actions". When my goal is to click e.g. "Format cell" this is confusing.

https://github.com/user-attachments/assets/f4132648-86c1-49aa-aa0d-63843c516d02

(Let me know if you would prefer these tiny bug reports somewhere else/not at all)

### Environment

{
  "marimo": "0.9.6",
  "OS": "Darwin",
  "OS Version": "22.3.0",
  "Processor": "arm",
  "Python Version": "3.12.6",
  "Binaries": {
    "Browser": "129.0.6668.91",
    "Node": "v22.9.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.10.1",
    "ruff": "0.6.7",
    "starlette": "0.39.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {}
}

### Code to reproduce

_No response_

### PR DESCRIPTION
**Pull request by mscolnick**
Don't hide the markdown on blur if interacting with vim search, sql dropdown, or cell actions dropdown.

Fixes #2594

### CODE REVIEW

File: frontend/src/components/editor/navigation/navigation.ts [hunk 1]
```diff
@@ -116,6 +133,27 @@ function useCellFocusProps(
...
+  if (!element) {
+    return false;
+  }
+  if (element instanceof HTMLElement) {
+    return element.closest(".cm-vim-panel") !== null;
+  }
+  return false;
+}
+
+function getDatForCellId(element: Element | null | undefined): CellId | null {
```
Comment (Light2Dark) [inline frontend/src/components/editor/navigation/navigation.ts]:
```suggestion
function getDataForCellId(element: Element | null | undefined): CellId | null {
```

**Review by Light2Dark — APPROVED** [review]
