### PR TITLE
fix: cell actions and notebook settings scroll

### LINKED ISSUE #4632: Cannot access items listed beyond screen height
### Describe the bug

As shown in the snapshot, cannot scroll or view what is listed beyond the screen height. The same behavior was observed with other long menus (ex: `Open cell actions` ("..." on a cell), simple right click on the screen).

Please can you add this to the backlog ? Currently, can access it only when the screen resolution/zoom-level is reduced.

Image

### Environment

<details>

```
{
  "marimo": "0.13.0",
  "OS": "Darwin",
  "OS Version": "24.3.0",
  "Processor": "i386",
  "Python Version": "3.12.7",
  "Binaries": {
    "Browser": "135.0.7049.85",
    "Node": "v22.13.1"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "narwhals": "1.14.2",
    "packaging": "24.1",
    "psutil": "6.0.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "starlette": "0.41.3",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.1",
    "websockets": "14.1"
  },
  "Optional Dependencies": {
    "altair": "5.5.0",
    "anywidget": "0.9.13",
    "duckdb": "1.1.3",
    "nbformat": "5.10.4",
    "openai": "1.75.0",
    "pandas": "2.2.3",
    "polars": "1.27.1",
    "pyarrow": "17.0.0",
    "pycrdt": "0.11.1",
    "ruff": "0.8.0",
    "sqlglot": "26.15.0"
  },
  "Experimental Flags": {}
}
```

</details>

### Code to reproduce

_No response_

### PR DESCRIPTION
**Pull request by mscolnick**
Fixes #4632

Clamp many popovers throughout the app, and make scrollable. Also make the notebook settings 2 columns.

Screenshot 2025-04-22 at 10 54 13 PM

------------

Screenshot 2025-04-22 at 10 54 05 PM

------------

Screenshot 2025-04-22 at 11 04 18 PM

### CODE REVIEW

File: frontend/src/components/ui/popover.tsx [hunk 1]
```diff
@@ -16,10 +16,18 @@ const PopoverContent = React.forwardRef<
...
   }
 >(
   (
-    { className, align = "center", sideOffset = 4, portal = true, ...props },
+    {
+      className,
+      align = "center",
+      sideOffset = 4,
+      portal = true,
+      scrollable = false,
```
Comment (mscolnick) [inline frontend/src/components/ui/popover.tsx:28]: this one is intentionally default false since not sure all the types of popovers we have

**Review by akshayka — APPROVED** [review]
