### PR TITLE
fix: query parameters in ws

### LINKED ISSUE #5376: Marimo 0.14 breaks query params (at least locally)
### Describe the bug

import marimo as mo

query_params = mo.query_params()

query_params

The above 3 lines of code no longer show query params when you set them locally in 0.14 and it used to work in 0.13.15 and all versions before

### Will you submit a PR?

- [ ] Yes

### Environment

0.14

### Code to reproduce

import marimo as mo

query_params = mo.query_params()

query_params

### PR DESCRIPTION
**Pull request by akshayka**
This fixes a regression that caused `mo.query_params()` to stop working. We need to send all query parameters to the backend, not just known ones, as part of the websocket URL.

Tested by playing with the query parameters smoke test (`_marimo/smoke_tests`).

Fixes #5376.

### CODE REVIEW

File: frontend/src/core/runtime/runtime.ts [hunk 1]
```diff
@@ -52,14 +52,10 @@ export class RuntimeManager {
       }
     }
 
-    // Move over window level parameters to the WebSocket URL
```
Comment (akshayka) [inline frontend/src/core/runtime/runtime.ts:55]: @dmadisetti Was there a reason for stripping unknown query parameters? This breaks `mo.query_params()`.

Was this code too aggressively refactored, i.e. is there a codepath that relies on query parameter stripping?

File: frontend/src/core/runtime/runtime.ts [hunk 2]
```diff
@@ -52,14 +56,14 @@ export class RuntimeManager {
...
-      const value = currentParams.get(key);
-      if (value !== null) {
-        baseUrl.searchParams.set(key, value);
+    for (const [key, value] of currentParams.entries()) {
+      if (
+        restrictToKnownQueryParams &&
+        !Object.values(KnownQueryParams).includes(key)
+      ) {
+        continue;
       }
```
Comment (akshayka) [inline frontend/src/core/runtime/runtime.ts:65]: I included this in case other code paths do need to restrict to known query parameters.

File: frontend/src/core/runtime/runtime.ts (hunk 1 above)
Comment (dmadisetti) [reply frontend/src/core/runtime/runtime.ts:55]: A little too conservative - with the refactor query params were not passed down at all. Thanks for the general fix

File: frontend/src/core/runtime/runtime.ts (hunk 2 above)
Comment (dmadisetti) [reply frontend/src/core/runtime/runtime.ts:65]: Likely not needed

**Review by dmadisetti — APPROVED** [review]
Thanks for the unit test too

File: frontend/src/core/runtime/runtime.ts (hunk 2 above)
Comment (akshayka) [reply frontend/src/core/runtime/runtime.ts:65]: Got it, so just don't filter known query params, pass all through?

Edit: nvm, saw your approval.
