### PR TITLE
Fix group dependency upgrade

### LINKED ISSUE #7203: UV package api calls from marimo ui ignore dependency groups
### Describe the bug

When upgrading a grouped package via the marimo UI the group is ignored and the package is added to the general project dependencies. 

The marimo API is missing the logic to:  
- Detect which dependency group (if any) the existing package belongs to, and
- pass the appropriate ```--group <name>``` when performing the upgrade.

Without that flag, uv add always writes the upgraded package straight into the main ```[project.dependencies]``` array.

I tried to track this down and submit my first pr that was more then a typo fix. But this is above my pay grade. I think that the API class does not contain the group -  Also I realize now that things like this may complicate it #6854 specifically my suggestion on pyproject.toml organization. 

 

### Will you submit a PR?

- [ ] Yes

### Environment

<details>

```
m-dev master  ❯ marimo env
{
  "marimo": "0.17.8",
  "editable": false,
  "location": "/home/mike/code/pub/m-dev/.venv/lib/python3.13/site-packages/marimo",
  "OS": "Linux",
  "OS Version": "6.17.7-1-3-ARCH",
  "Processor": "",
  "Python Version": "3.13.7",
  "Locale": "en_US",
  "Binaries": {
    "Browser": "--",
    "Node": "v25.1.0"
  },
  "Dependencies": {
    "click": "8.3.1",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.10",
    "narwhals": "2.12.0",
    "packaging": "25.0",
    "psutil": "7.1.3",
    "pygments": "2.19.2",
    "pymdown-extensions": "10.17.1",
    "pyyaml": "6.0.3",
    "starlette": "0.50.0",
    "tomlkit": "0.13.3",
    "typing-extensions": "4.15.0",
    "uvicorn": "0.38.0",
    "websockets": "15.0.1"
  },
  "Optional Dependencies": {
    "loro": "1.8.2",
    "mcp": "1.21.2",
    "pytest": "9.0.1"
  },
  "Experimental Flags": {}
}

```

</details>

### Code to reproduce

_No response_

### PR DESCRIPTION
**Pull request by Deufel**
### Backend   
Replaced `dev: bool` parameter with `group: Optional[str] = None` across package managers and API endpoints  
### Frontend  
Updated `UpgradeButton`, `RemoveButton`, and `InstallButton` to extract and pass the group from package tags

Tests: Updated to use `group="dev"` instead of `dev=True` , No New Tests

**This is a breaking change to the internal API**, but generalizes the previous dev-only behavior to support arbitrary dependency groups.

## 📋 Checklist

- [X] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [ ] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [ ] I have added tests for the changes made. * on hold for official team review
- [X] I have run the code and verified that it works as expected.

### CODE REVIEW

**Comment by Deufel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Deufel** [comment]
```bash
 .../components/app-config/optional-features.tsx    |  2 +-
 .../editor/chrome/panels/packages-panel.tsx        | 20 +++++--
 marimo/_runtime/packages/conda_package_manager.py  | 14 +++--
 marimo/_runtime/packages/package_manager.py        | 16 +++---
 marimo/_runtime/packages/pypi_package_manager.py   | 66 +++++++++++-----------
 marimo/_server/api/endpoints/packages.py           |  8 +--
 marimo/_server/models/packages.py                  |  4 +-
 tests/_runtime/packages/test_package_managers.py   |  8 +--
 .../_runtime/packages/test_pypi_package_manager.py | 20 +++----
 tests/_server/api/endpoints/test_packages.py       | 18 +++---
 10 files changed, 93 insertions(+), 83 deletions(-)

 ```

**Comment by mscolnick** [comment]
@Deufel - apologies we haven't gotten to reviewing this yet. we are prepping for a large release and has been taking a lot of our time. we should hopefully have time end of this week or early next week

**Comment by Deufel** [comment]
O no worries at all, thanks letting me know :+1:

**Comment by manzt** [comment]
Hi @Deufel having a look at this. I notice still in draft. Is this now ready for review?

**Comment by Deufel** [comment]
Sorry for the delay, I had left in draft as was not sure if the direction was appropriate. I updated it so that it is synced with the last major release + added some tests. Nothing in the core approach changed. 

### Summary
#### Changes:

Replaced dev: bool with group: Optional[str] in add/remove requests
Frontend extracts group from tags and passes to API
UvPackageManager uses --group <name> flag
Added DependencyTag struct for proper typing (this addressed a @ts-expect-error comment in the code noting the backend tag types didn't match frontend expectations)

#### Rationale: 
Using --group <name> follows uv's CLI convention and handles the general case. The old --dev flag was a special case of this.

#### Testing:

Added unit tests for custom group install and uninstall
Manually tested upgrade flow with a test uv project 
updated existing tests where dev expects a bool **API CHANGE**

#### Known limitation: 
Packages appearing via include-group show the parent group, not their declaration group. Resolving this feels like a product decision — it depends on how Marimo wants to represent uv's dependency model. Curious as to what you guys think here. My research is that this is a bit of a UV limitation and is non trivial to address fully. 

Let me know if you have any other questions.

Thanks! -Mike

<hr> 
Demo pyproject.toml to see the limitation; (and you can use this to see the improvements over the current approach as well)

```toml

[project]
name = "test-include-groups"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
docs = [
    "sphinx>=6.0.0",
]
dev = [
    {include-group = "docs"},
    "pytest",
    "marimo"
]

[tool.uv.sources]
marimo = { path = "MARIMO_DEV_PATH", editable = true } # to use dev version of marimo 
[tool.uv]
default-groups = ["dev", "docs"]
```
use this pyproject.toml -> `uv sync` -> `uv run marimo edit`  -> upgrade the sphinx package and then take a look at the pyproject.toml

File: frontend/src/components/editor/chrome/panels/packages-panel.tsx [hunk 1]
```diff
@@ -604,12 +605,14 @@ const DependencyTreeNode: React.FC<{
...
+              packageName={node.name}
+              tags={node.tags}
+              onSuccess={onSuccess}
+            />
+
             <RemoveButton
               packageName={node.name}
-              // FIXME: Backend types are wrong/outdated.
-              // tags actually have the shape: Array<{ kind: string; value: string }>
-              // @ts-expect-error — backend tag types do not match frontend expectations yet
```
Comment (manzt) [inline frontend/src/components/editor/chrome/panels/packages-panel.tsx:612]: Nice

File: P_empty
Comment (manzt) [inline P_empty:1]: Should delete

**Review by manzt — APPROVED** [review]
Thanks  @Deufel  The approach looks good to me.

I think the `include-group` limitation is fine for now. Good that it's known, and if it becomes an issue we can revisit, but for the current use case this is totally acceptable.

I pushed a small fix to the test just removed a stale `--compile` flag from the expected args that was causing CI to fail, some empty files, and rebased on main to get the latest API changes resolved.

Looks good to merge once CI is green.
