### PR TITLE
fix: focus on editors and buttons after layout shift from hidden code

### LINKED ISSUE #7487: Long hidden cells cause visual jumps when collapsed
### Describe the bug

If I am editing a long hidden cell, then click on another cell to edit it, the cell will shift up, but the view won't.

Example:

https://github.com/user-attachments/assets/fabe16e6-21c8-4c00-baba-6295b7baae50

### Will you submit a PR?

- [ ] Yes

### Environment

<details>

Not sure how to get this on molab. I think molab is on 0.18.1, but I've seen it on 0.18.4.

</details>

### Code to reproduce

https://molab.marimo.io/notebooks/nb_GCHJKvYsepfG5dZ1SEuqFh

### PR DESCRIPTION
**Pull request by mscolnick**
Fixes #7487

It may not (or ever) feel perfect; layout shifts will be inevitable. But this does return the focus to the selected line or button or editor after closing a temporarily shown cell (temporarily shown --> marked hidden, but was focused)

### CODE REVIEW

File: frontend/src/components/editor/navigation/focus-utils.ts [hunk 1]
```diff
@@ -29,6 +29,38 @@ export function focusCell(cellId: CellId): void {
   }
 }
 
+/**
+ * First tries to scroll the active line into view, if the cell is focused.
+ * If not, it scrolls the cell container into view.
+ */
+export function scrollCellIntoView(cellId: CellId): void {
```
Comment (Light2Dark) [inline frontend/src/components/editor/navigation/focus-utils.ts]: There's a file called scrollCellIntoView.ts. Should this live there and/or renamed?

File: frontend/src/components/editor/cell/cell-actions.tsx [hunk 2]
```diff
@@ -57,11 +60,28 @@ const CellActionsDropdownInternal = (
...
   const [open, setOpen] = useState(false);
   const closePopover = () => setOpen(false);
+  const buttonRef = useRef<HTMLButtonElement>(null);
   const actions = useCellActionButtons({ cell: props, closePopover });
 
   // store the last focused element so we can restore it when the popover closes
   const restoreFocus = useRestoreFocus();
 
+  useEffect(() => {
+    if (open) {
```
Comment (Light2Dark) [inline frontend/src/components/editor/cell/cell-actions.tsx]: any thoughts on this lint comment? I think we could make a `handleOpen` function and call this wherener setOpen()

Comment (Light2Dark) [reply frontend/src/components/editor/cell/cell-actions.tsx]: oh, the lint comment is `Avoid using state and effects as an event handler. Instead, call the event handling code directly when the event occurs`

Comment (mscolnick) [reply frontend/src/components/editor/cell/cell-actions.tsx]: yea i can make a `handleOpen` callback
