### PR TITLE
fix: limit console outputs to last 5000 lines per cell

### LINKED ISSUE #1380: Very large console outputs can make Chrome tab unresponsive
### Describe the bug

If you create a cell that prints a LOT of console outputs, the frontend becomes unresponsive (hard to scroll, things don't render, buttons don't work) and Chrome prompts you to kill it.

It's never a good idea to print this much stuff, but sometimes it happens accidentally -- in this case better to show the last N lines rather than become unresponsive.

Additionally, this affected the entire Home server and all open notebooks -- all open tabs became unresponsive -- even though only one of the notebooks had the extremely large console output.

### Environment

```
{
  "marimo": "0.5.2",
  "OS": "Linux",
  "OS Version": "6.5.0-27-generic",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "123.0.6312.122",
    "Node": "v18.13.0"
  },
  "Requirements": {
    "click": "8.1.3",
    "importlib-resources": "6.1.0",
    "jedi": "0.19.0",
    "markdown": "3.4.4",
    "pymdown-extensions": "10.3",
    "pygments": "2.16.1",
    "tomlkit": "0.12.0",
    "uvicorn": "0.24.0.post1",
    "starlette": "0.27.0",
    "websocket": "missing",
    "typing-extensions": "4.8.0",
    "black": "23.3.0"
  }
}
```

### Code to reproduce

```python
for i in range(1000000):
    print(i)
```

### PR DESCRIPTION
**Pull request by akshayka**
# Pull Request Template

## 📝 Summary

Limit console outputs to last 5000 lines per cell. Fixes #1380 

## 🔍 Description of Changes

This PR limits the number of lines shown in the console output per cell to avoid overloading the frontend. The tail of the console output is shown, limited to 5000 lines.

## 🛠️ Additional Information

The number 5000 was chosen by comparison to Google Colab.

image

## 📋 Checklist Before Submitting

- [x] I have read the [contributor guidelines](../CONTRIBUTING.md) and the Pull Request section.
- [x] This PR fixes an issue (If applicable, specify issue number #).
- [x] This change was discussed or approved through an issue or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [x] I have added necessary tests for the changes made.
- [x] I have run the code and verified that it works as expected.

## 🧩 Related Issues

Fixes #1380 

## 📜 Who Can Review?

@akshayka OR @mscolnick

### CODE REVIEW

File: frontend/src/core/cells/collapseConsoleOutputs.tsx [hunk 1]
```diff
@@ -89,3 +90,41 @@ function handleCarriageReturns(
...
+    const n_lines_to_keep = limit - n_lines_after_output;
+    return [
+      warningOutput,
+      { ...output, data: output_lines.slice(-n_lines_to_keep).join("\n") },
+      ...consoleOutputs.slice(cutoff + 1),
+    ];
+  } else {
+    return [warningOutput, ...consoleOutputs.slice(cutoff + 1)];
+  }
+}
```
Comment (mscolnick) [inline frontend/src/core/cells/collapseConsoleOutputs.tsx:130]: probably worth adding a small snapshot test for `truncateHead`.

Comment (akshayka) [reply frontend/src/core/cells/collapseConsoleOutputs.tsx:131]: @mscolnick Thanks, added some unit tests.
